### PR TITLE
Added a list_count command

### LINKED ISSUE #64: Notification list expansion
We would like to expand on the current notification list fucntionality with the following commands:

list_count 'list_name'
--> prints the list count

list_subs 'list_name'
-->prints the list members (could also include the count)

### PR DESCRIPTION
**Pull request by VandeVelGianni**
List_count gives the amount of users subbed to a specified list, list_users gives the list of users and the amount of subscribed users.

### CODE REVIEW

**Comment by Eva774** [comment]
I do not really see a legitimate use case for the list_users command except for curiosity and it could be argued that this is in conflict with our privacy policy since that states _"We will not track any user data, except for your user ID, as this is required to notify you."_ and in this feature we are using the user ID for something other than notifying the user.

**Comment by VandeVelGianni** [comment]
That same information is used to notify the users. Maybe it could be a feature only for admin-use so they can skim the lists without notifying, but I'm obviously willing to just remove that part of the PR.

**Comment by Eva774** [comment]
It is indeed the same information as the one used to notify the users, but in this case we are using the information for something other than notifying and that makes me a bit hesitant.
Even as an admin-only, I guess I just don't really see a legit case where you would need the names. In all scenarios I can think of (say for example you would want to see whether a list can be deleted), the count and the last used date would provide enough info. And if you really need the names of users, you can just notify them, at least then they know that you are using their information. 

I am going to let some the other @nerdland-unofficial-fans/bot-admins weigh in on this :)

**Review by Eva774 — APPROVED** [review]

**Review by bobvdvleuten — APPROVED** [review]
🚢 that stuff

**Pull request merged**
